### ISSUE TITLE
Microsoft Edge auto-translate bug on JP Tekxach page

### ISSUE THREAD

**Issue by GlaucaBlitz** [HazmatDrone/hazmatdr.one#24]
Tekxach's icon misplaced into Drakkite link.
Steps to reproduce:
1) Open [Tekxach JP ref page](https://hazmatdr.one/tekxach/jp/) using Microsoft Edge.
2) Use the browser's built-in auto-translate.
![image](https://user-images.githubusercontent.com/73702239/139572824-fedaa87e-34e2-48e8-ab2e-33f0b5db8793.png)

**Comment by HazmatDrone** [comment]
Both the Tekxach and Drakkite icons are misplaced in this screenshot.

**Comment by HazmatDrone** [comment]
May have been fixed in 52cf01b. Please test again and close the issue if it has been fixed.
